[package]
name = "forge"
version = "0.2.0"
edition = "2024"

[features]
acpi = []
multi_core = []
serial_debug = []
qemu_debug = []
system76_ec_debug = []
syscall_debug = []
userspace = []
x86_kvm_pv = []
pti = []
std = []
debugger = []
profiling = []
lpss_debug = []
dtb = []
sys_fdstat = []
self_modifying = []

[dependencies]
font8x8 = { version = "0.3.1", default-features = false, features = [
    "unicode",
] }
linked_list_allocator = "0.10.5"
x86_64 = "0.14.10"
pc-keyboard = "0.7.0"
pic8259 = "0.10.1"
uart_16550 = "0.2.18"
spin = "0.9.8"
futures-util = { version = "0.3.30", default-features = false, features = [
    "alloc",
] }
bitflags = "2.4.1"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
volatile = "0.4.6"
indexmap = { version = "2.7.0", default-features = false }
redstone_path = { path = "../redstone/path" }
hashbrown = "0.14"
arrayvec = { version = "0.7", default-features = false }

x86 = "0.52"
redstone_syscall = { path = "../redstone/syscall" }
raw-cpuid = "10.7.0"
object = { version = "0.36", default-features = false, features = [
    "elf",
    "read_core",
    "unaligned",
    "archive",
] }
rustc-demangle = "0.1"
slab = { version = "0.4", default-features = false }
